
modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="create_cogs_invaders"
version="${mod_version}"
displayName="Create Cogs Invaders"
authors="Lalusko"
description='''
Esqueleto del mod con soporte opcional para GeckoLib, Create y JEI.
'''

[[dependencies.create_cogs_invaders]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_cogs_invaders]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_cogs_invaders]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.7.0,5.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_cogs_invaders]]
    modId="create"
    mandatory=true
    versionRange="[6.0.6,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_cogs_invaders]]
    modId="jei"
    mandatory=false
    versionRange="[*]"
    ordering="NONE"
    side="CLIENT"
